spring:
  application:
    name: OnlineShoop
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: b1t
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml